STARTED:[2015-02-27|08:22:08]
[EXCEPTION] [2015-02-27|08:22:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:22:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|08:23:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|15:48:53] An Exception occurred!
''
[EXCEPTION] [2015-02-27|15:48:53] An Exception occurred!
''
[EXCEPTION] [2015-02-27|15:48:53] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1194, in do_open
    r = h.getresponse()
  File "C:\Python34\lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
[EXCEPTION] [2015-02-27|15:48:53] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1194, in do_open
    r = h.getresponse()
  File "C:\Python34\lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
[EXCEPTION] [2015-02-27|15:48:53] Moving on... Tired of getting SMSs about this...
[EXCEPTION] [2015-02-27|15:48:53] Moving on... Tired of getting SMSs about this...
[EXCEPTION] [2015-02-27|15:48:53] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HOwo9PT09PT09PT09PT09PT09PT09PT09PT09Ck9oIEJveSEgQW4gSW5jb21pbmcgQ2FsbCEKPT09PT09PT09PT09PT09PT09PT09PT09PQo=
[EXCEPTION] [2015-02-27|15:48:53] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTU6NDg6NTJdIFRyeWluZzogQVRI
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:55] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:56] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:57] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:58] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:01:59] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:00] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:01] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:02] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:03] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:04] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:05] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:07] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:09] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:10] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:11] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:12] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:13] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:14] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:15] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:16] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:17] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:18] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:19] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:20] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:21] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:22] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:23] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:24] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:25] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:26] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:27] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:28] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:29] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:30] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:31] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:32] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:33] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:34] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:35] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:36] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:37] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:38] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:40] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:41] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:42] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:43] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:44] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:45] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:46] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:47] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:48] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:49] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:50] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:51] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:52] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:53] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:02:54] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:03:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:03:06] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:03:08] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:03:39] Sending SMS to Tropo...
[EXCEPTION] [2015-02-27|16:28:40] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 404: Not Found
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 404: Not Found
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:10] URL Error... Timeout?
HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:29:40] Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 499, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
[EXCEPTION] [2015-02-27|16:34:47] >>>> Retrying request: http://api.tropo.com/1.0/sessions?action=create&token=1950c84caa3aa1489428e3946049fdfa96c92736612b6abb738b004d0c8f12c253ae0bdec48ab3828dd1d89d&msg=Polly%20Dongle%20SOS!%20An%20Exception%20occurred!%20call%20to%20ClearCommError%20failed&calltype=GuinDongleStatusSMS&ph=19543679247&callerid=%2B14122677909
[EXCEPTION] [2015-02-27|16:34:48] >>>> Retrying request: http://api.tropo.com/1.0/sessions?action=create&token=1950c84caa3aa1489428e3946049fdfa96c92736612b6abb738b004d0c8f12c253ae0bdec48ab3828dd1d89d&msg=Polly%20Dongle%20SOS!%20An%20Exception%20occurred!%20call%20to%20ClearCommError%20failed&calltype=GuinDongleStatusSMS&ph=19543679247&callerid=%2B14122677909
[EXCEPTION] [2015-02-27|16:34:49] >>>> Retrying request: http://api.tropo.com/1.0/sessions?action=create&token=1950c84caa3aa1489428e3946049fdfa96c92736612b6abb738b004d0c8f12c253ae0bdec48ab3828dd1d89d&msg=Polly%20Dongle%20SOS!%20An%20Exception%20occurred!%20call%20to%20ClearCommError%20failed&calltype=GuinDongleStatusSMS&ph=19543679247&callerid=%2B14122677909
[EXCEPTION] [2015-02-27|17:03:27] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:27] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:29] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:29] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:30] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:30] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:30] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:30] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:39] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:03:39] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:04:47] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HOytDUklORyBSZXNwb25zZTogDQorQ1JJTkc6IFZPSUNFDQoNCitDTElQOiAiMDAxOTU0MzY3OTI0NyIsMSwiIiwsIiIsMA0K
[EXCEPTION] [2015-02-27|17:04:48] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO0hUVFAgUmVzcG9uc2U6CgpZb3VyIElQIGlzIDQxLjc5LjIzNi4xOQpUaGVyZSBhcmUgYWxyZWFkeSBQZW5kaW5nL0luIFByb2dyZXNzIENhbGwtbWUtYmFjayByZXF1ZXN0cyBmcm9tIHRoaXMgcGhvbmUgbnVtYmVyLgo=
[EXCEPTION] [2015-02-27|17:04:48] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO0RFVklDRSBTVEFURTogUkVBRFk=
[EXCEPTION] [2015-02-27|17:04:48] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HOytDUEFTIFJlc3BvbnNlOiBBVCtDUEFTDQ0KK0NQQVM6IDANCg0KT0sNCg==
[EXCEPTION] [2015-02-27|17:04:49] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO0hUVFAgUmVxdWVzdCBHZW5lcmF0ZWQ6IGh0dHA6Ly8xMjguMi4yMDguMTkxL3dhL0RCU2NyaXB0cy9jcmVhdGVNaXNzZWRDYWxsLnBocD9waD0wMDE5NTQzNjc5MjQ3JnN5c2xhbmc9QW1lckVuZ2xpc2gmbXNnbGFuZz1BbWVyRW5nbGlzaCZjaD1HdWluRG9uZ2xlJmljY2lkPTg5MjI0NjUwMTA1NjAxMzAwN0ZGJnRpbWVvZnJlcT0yMDE1LTAyLTI3JTIwMTclM0EwMyUzQTE3
[EXCEPTION] [2015-02-27|17:12:54] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:12:54] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:12:57] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:12:57] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:04] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:04] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:06] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:06] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:07] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:07] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:09] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:09] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:10] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:10] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:13:12] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|17:14:47] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1JTU0k6IDEy
[EXCEPTION] [2015-02-27|17:14:48] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6MzVdIEhhbmcgdXAgc3VjY2Vzc2Z1bCE=
[EXCEPTION] [2015-02-27|17:14:48] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6NDJdIFRyeWluZzogQVQrQ0hVUA==
[EXCEPTION] [2015-02-27|17:14:49] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6NDVdIFRyeWluZzogQVQrQ0hDQ1M=
[EXCEPTION] [2015-02-27|17:14:49] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6NDVdIFJlc3BvbnNlOiBBVCtDSENDUw0NCkNPTU1BTkQgTk9UIFNVUFBPUlQNCg==
[EXCEPTION] [2015-02-27|17:14:50] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6NDhdIApDb3VsZCBub3QgdGVybWluYXRlIGNhbGwgdXNpbmcgYW55IGtub3duIEFUIGNvbW1hbmRzLi4uCkdvb2dsZSBWb2ljZSBhbmQgU2t5cGUgYXJlIGtub3duIHRvIGhhdmUgdGhpcyBwcm9ibGVtLiAKSXMgdGhlIGNhbGxlciB1c2luZyBhIFZPSVAgc2VydmljZT8KCkF0dGVtcHRpbmcgdG8gcmVzdGFydCBjb25uZWN0aW9uLi4u
[EXCEPTION] [2015-02-27|17:14:50] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6NDldIEhhbmcgdXAgdW5zdWNjZXNzZnVsISBUcnlpbmcgdG8gcmVnaXN0ZXIgY2FsbGVyIGFueXdheS4uLg==
[EXCEPTION] [2015-02-27|17:14:50] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1JTU0k6IDEy
[EXCEPTION] [2015-02-27|17:14:51] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HOytDUEFTIFJlc3BvbnNlOiBBVCtDUEFTDQ0KK0NQQVM6IDANCg0KT0sNCg==
[EXCEPTION] [2015-02-27|17:14:51] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO0RFVklDRSBTVEFURTogUkVBRFk=
[EXCEPTION] [2015-02-27|17:14:51] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNl0gWzIwMTUtMDItMjd8MTc6MTI6NTFdIExvZ2dpbmcgZGlhZ25vc3RpYyB2ZWN0b3IuLi4=
[EXCEPTION] [2015-02-27|19:30:28] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|19:30:28] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|19:34:47] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO1tDT00yNF0gWzIwMTUtMDItMjd8MTk6MzA6MDddIFdhaXRpbmcgZm9yIGEgY2FsbCBmcm9tIEdvZG90Li4uIE5vdGhpbmcgdG8gYmUgZG9uZS4uLgo=
[EXCEPTION] [2015-02-27|20:30:28] URL Error... Timeout?
<urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|20:30:28] Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 509, in create_connection
    raise err
  File "C:\Python34\lib\socket.py", line 500, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PD\Documents\polly\pythonDongle\remote_monitor.py", line 15, in send_request
    wp = urllib2.urlopen(http_request, timeout=d.web_request_timeout)
  File "C:\Python34\lib\urllib\request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python34\lib\urllib\request.py", line 1192, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
[EXCEPTION] [2015-02-27|20:34:47] >>>> Retrying request: http://128.2.211.183/wa/RemoteMonitor/dongleMontiorUpdate.php?update=TE9HO0FQUExJQ0FUSU9OOiBwb2xseV9nYW1l
